implement logExecutionTimeBpp
ajax-malov-n/stockanalyzer pull request #2
Opened 2024-08-22 15:56 UTC by ajax-malov-n

+ Implementation of BeanPostProcessor

2024-08-22 20:41 UTC, viacheslav-torbin commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +    }
IMHO, try-catch looks ugly here. You can probably do it like this:
```kotlin
        val matchingMethod = clazz.declaredMethods.firstOrNull { 
            it.name == method.name && it.parameterTypes.contentEquals(method.parameterTypes)
        }
        return matchingMethod?.isAnnotationPresent(LogExecutionTime::class.java) ?: false
```

2024-08-23 07:17 UTC, ajax-butriy-v commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +        if (beanClass != null) {
May be **return beanClass?.let { logic } ?: bean** (although in fact it has same logic as yours)

2024-08-23 07:56 UTC, ajax-gnatiuk-s requested changes
Let's add extra functionality to make your BPP less trivial.
Please, add option to enable/disable profiling using config properties

2024-08-23 07:56 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +                    val result = method.invoke(bean, *(args ?: emptyArray()))
what if the function throw exception?

2024-08-23 07:56 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +                    log.info("Execution time of ${method.name} is ${(System.nanoTime() - before) / 1_000_000} ms")
Never inline parameters into log message.

❌ Incorrect usage:
```kotlin
val some = 123
logger.info("Logging parameter=$some using inlining into the message")
```

✅ correct:
```kotlin
val some = 123
logger.info("Logging parameter={} using message pattern", some)

```

2024-08-23 07:56 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +        }
let's practice kotlin's `sequence`.

Please, rework this function by using [generate-sequence](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/generate-sequence.html)

2024-08-23 07:56 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +            return false
let's rework this function as well.

In general it's bad practice to use exceptions for a flow control.
It's better to refactor in the next way:
1. obtain all methods
2. find the required method in list

2024-08-26 09:24 UTC, ajax-butriy-v commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +    private val beanMap = HashMap<String, Pair<Class<*>, List<Method>>>()
may be extract `Pair<Class<*>, List<Method>>` to a separate data class for readability?

2024-08-26 09:24 UTC, ajax-butriy-v commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +    }
all other members use `return` statement, while this one has expression body

2024-08-26 18:03 UTC, ajax-gnatiuk-s requested changes

2024-08-26 18:03 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTime.kt
> +annotation class LogExecutionTime()
```suggestion
annotation class LogExecutionTime
```

2024-08-26 18:03 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +    private fun areMethodsEqual(originalMethod: Method, proxiedMethod: Method): Boolean {
Let's practice infix function?

```kotlin
// invocation part:
val equals = proxiedMethod isEqualTo originalMethod
```
Isn't it beautiful?

Or, at least extension function.

The suggestion in **optional**, so, if you don't want apply the suggestion then just resolve the thread.

2024-08-26 18:03 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +            log.info("Execution time of {} is {} ms", proxiedMethod.name, executionTimeInMs)
`System.nanoTime()` is used but logged as `ms`.

Also, the variable `executionTimeInMs` lies about it's measurement units.

2024-08-26 18:03 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +    private fun logMethodExecution(
the function does:
- invoke target bean function
- log execution time

But `logMethodExecution` tells only about the logging and nothing about the invocation

2024-08-26 18:03 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +        return methods.any { originalMethod ->
What complexity we have here?

2024-08-26 18:03 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +    data class ClassWithAnnotatedMethods(val clazz: Class<*>, val methods: List<Method>)
should it be private?

----

I'd like to see an internal classes after all members of the host class

2024-08-29 06:28 UTC, ajax-gnatiuk-s reviewed
LGTM

should we add some tests?

2024-08-29 06:31 UTC, ajax-gnatiuk-s commented on src/main/kotlin/systems/ajax/malov/stockanalyzer/config/beanpostprocessor/LogExecutionTimeAnnotationBeanPostProcessor.kt
> +        return methods.any { originalMethod ->
we talk about this offline. Are going to make complexity closer to `O(1)`?

2024-08-30 19:25 UTC, ajax-gnatiuk-s approved these changes
LGTM

2024-09-02 06:56 UTC, merged